#!/bin/zsh

privateip=$(aws ec2 describe-instances --instance-id $2 | jq -r '.Reservations[].Instances[].PrivateIpAddress')
node=$(kubectl get nodes -o json | jq '.items[] | select(.status.addresses[].address=="'$privateip'") | .metadata.name')

kubectl $1 node $(echo $node | tr -d '"')
